### ISSUE TITLE
Could not purchase at all

### ISSUE THREAD

**Issue by TwinZA** [TheoKah/CarrotShop#26] opened 2018-01-31 21:45 UTC
When attempting to purchase I won't take any money or give anything

**Comment by TheoKah** [comment] 2018-01-31 22:05
Sorry to hear that.

What version of minecraft, sponge and plugin is it?
Do you have an error in console?

What items and what is written on the sign?

**Comment by TwinZA** [comment] 2018-01-31 22:23
Latest version, Latest version of sponge 1.12.2 and it is [iBuy] 20 and it says something like do you want to buy blank? I saw a older thread saying right click and when i right click it does not do anything

**Comment by TheoKah** [comment] 2018-01-31 22:29
Are you using a single currency or multiple?
Is it a modded item you are trying to sell?

Do you have a trace in console when creation or use of the sign?

**Comment by TwinZA** [comment] 2018-01-31 22:32
Single currency , No, but it will later , No

**Comment by TheoKah** [comment] 2018-01-31 22:37
Make sure you are using the CarrotShop-1.16-S7.0-MC1.12.2.jar version
 https://github.com/TheoKah/CarrotShop/releases/tag/1.16

If you are using the correct one, I'll have to check further. I wont be able to before tomorrow though

**Comment by TwinZA** [comment] 2018-01-31 22:44
I am please check further

**Comment by TheoKah** [comment] 2018-02-01 21:39
I were not able to reproduce the bug

Can you try to setup a trade sign see if it works?
Can you check your economy plugin is present and correctly loaded?

**Comment by TwinZA** [comment] 2018-02-02 21:50
A trade sign does work. I am quite sure my economy plugin is working

**Comment by TheoKah** [comment] 2018-02-02 22:15
So you can use /bal and /econ?
Can you give me your plugin list?

**Comment by TwinZA** [comment] 2018-02-02 23:40
Yes, Total Economy,Gp,Holograms,luckperms and nucleus

**Comment by TwinZA** [comment] 2018-02-02 23:40
And a custom

**Comment by SarcasticPig** [comment] 2018-02-05 22:09
I am unaware if this is the same issue, but when players on my server go to buy some items, despite having enough items in their inventory to sell, it will say "You do not have enough items to sell." It seems to occur randomly, not all the time. 

Plugins include: Economy Lite, Enjin Minecraft Plugin, GP, Kai's Commons, LuckPerms, MCClans, Nucleus, SimpleAntiAFK, VoxelSniper

**Comment by TheoKah** [comment] 2018-02-05 22:29
This is a different problem.

About the 1st problem: I do not remember if I tested with totaleconomy. I'll do that asap.

About the 2nd problem, can you open a new issue? Let me know there what the items are.

**Comment by TwinZA** [comment] 2018-02-06 00:25
Please test Total Economy as it is the only good Economy Plugin I found for sponge.

**Comment by TheoKah** [comment] 2018-02-24 18:18
Hi,

I tried with Total Economy 1.7.1 and had no problems
I released v1.17 is it still occuring?

If yes, can you provide step by step actions for me to reproduce the problem?

**Comment by Tollainmear** [comment] 2018-03-21 05:41
is the shop's position near the world spawn point and less than 16 block?
the spawn point might be protected by server.

**Comment by TheoKah** [comment] 2018-09-08 11:05
No answer. Closing. Feel free to reopen if you still have troubles

**Closed as completed by TheoKah** 2018-09-08 11:05 UTC
